"""adding configs to agent

Revision ID: 1ad46f6e4c2d
Revises: e1e15ff9ab6e
Create Date: 2024-06-26 20:51:04.227418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ad46f6e4c2d'
down_revision: Union[str, None] = 'e1e15ff9ab6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('llm_config', sa.JSON(), nullable=False))
    op.add_column('agent', sa.Column('embedding_config', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'embedding_config')
    op.drop_column('agent', 'llm_config')
    # ### end Alembic commands ###
