"""agent model updates

Revision ID: 80b6686ed43f
Revises: 560b00fd8d87
Create Date: 2024-08-26 17:17:49.840694

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "80b6686ed43f"
down_revision: Union[str, None] = "560b00fd8d87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent", sa.Column("description", sa.String(), nullable=True))
    op.add_column("agent", sa.Column("metadata_", sa.JSON(), nullable=False))
    op.drop_column("agent", "_metadata")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent", sa.Column("_metadata", postgresql.JSON(), autoincrement=False, nullable=False))
    op.drop_column("agent", "metadata_")
    op.drop_column("agent", "description")
    # ### end Alembic commands ###
