"""empty message

Revision ID: 0c315956709d
Revises: 9a505cc7eca9
Create Date: 2024-10-30 17:08:09.638235

"""

from typing import Sequence, Union

import sqlalchemy as sa

import letta.metadata
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c315956709d"
down_revision: Union[str, None] = "9a505cc7eca9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("organizations", "organization")
    op.rename_table("tools", "tool")
    op.rename_table("users", "user")

    op.add_column("organization", sa.Column("deleted", sa.Boolean(), nullable=False))
    op.add_column("organization", sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True))
    op.add_column("organization", sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False))
    op.add_column("organization", sa.Column("_created_by_id", sa.String(), nullable=True))
    op.add_column("organization", sa.Column("_last_updated_by_id", sa.String(), nullable=True))
    op.add_column("tool", sa.Column("deleted", sa.Boolean(), nullable=False))
    op.add_column("tool", sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True))
    op.add_column("tool", sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True))
    op.add_column("tool", sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False))
    op.add_column("tool", sa.Column("_created_by_id", sa.String(), nullable=True))
    op.add_column("tool", sa.Column("_last_updated_by_id", sa.String(), nullable=True))
    op.add_column("tool", sa.Column("_organization_id", sa.String(), nullable=False))
    op.add_column("user", sa.Column("deleted", sa.Boolean(), nullable=False))
    op.add_column("user", sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True))
    op.add_column("user", sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False))
    op.add_column("user", sa.Column("_created_by_id", sa.String(), nullable=True))
    op.add_column("user", sa.Column("_last_updated_by_id", sa.String(), nullable=True))
    op.add_column("user", sa.Column("_organization_id", sa.String(), nullable=False))
    op.create_foreign_key(None, "tool", "organization", ["_organization_id"], ["_id"])
    op.create_foreign_key(None, "user", "organization", ["_organization_id"], ["_id"])

    op.add_column("agents", sa.Column("tool_rules", letta.metadata.ToolRulesColumn(), nullable=True))
    op.alter_column("block", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("block", "label", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("block", "label", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("block", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("agents", "tool_rules")
    op.drop_column("user", "_organization_id")
    op.drop_column("user", "_last_updated_by_id")
    op.drop_column("user", "_created_by_id")
    op.drop_column("user", "is_deleted")
    op.drop_column("user", "updated_at")
    op.drop_column("user", "created_at")
    op.drop_column("user", "deleted")
    op.drop_column("tool", "_organization_id")
    op.drop_column("tool", "_last_updated_by_id")
    op.drop_column("tool", "_created_by_id")
    op.drop_column("tool", "is_deleted")
    op.drop_column("tool", "updated_at")
    op.drop_column("tool", "created_at")
    op.drop_column("tool", "deleted")
    op.drop_column("organization", "_last_updated_by_id")
    op.drop_column("organization", "_created_by_id")
    op.drop_column("organization", "is_deleted")
    op.drop_column("organization", "updated_at")
    op.drop_column("organization", "created_at")
    op.drop_column("organization", "deleted")
    op.rename_table("user", "users")
    op.rename_table("tool", "tools")
    op.rename_table("organization", "organizations")
    # ### end Alembic commands ###
