"""Migrate messages to ORM

Revision ID: 43b3ad216686
Revises: 5987401b40ae
Create Date: 2024-12-04 11:35:39.851418

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "43b3ad216686"
down_revision: Union[str, None] = "5987401b40ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True))
    op.add_column("messages", sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False))
    op.add_column("messages", sa.Column("_created_by_id", sa.String(), nullable=True))
    op.add_column("messages", sa.Column("_last_updated_by_id", sa.String(), nullable=True))
    op.alter_column("messages", "tool_calls", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=False)
    op.alter_column("messages", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False)
    op.create_foreign_key(None, "messages", "agents", ["agent_id"], ["id"])
    op.create_foreign_key(None, "messages", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.alter_column("messages", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True)
    op.alter_column("messages", "tool_calls", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=True)
    op.drop_column("messages", "_last_updated_by_id")
    op.drop_column("messages", "_created_by_id")
    op.drop_column("messages", "is_deleted")
    op.drop_column("messages", "updated_at")
    # ### end Alembic commands ###
