"""Add FileMetadata table and drop Documents table

Revision ID: 7fb2327c830b
Revises: 9a505cc7eca9
Create Date: 2024-10-11 18:07:21.765653

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from letta.agent_store.db import CommonVector

# revision identifiers, used by Alembic.
revision: str = "7fb2327c830b"
down_revision: Union[str, None] = "9a505cc7eca9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("passages", "embedding", existing_type=sa.NUMERIC(), type_=CommonVector(), existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("passages", "embedding", existing_type=CommonVector(), type_=sa.NUMERIC(), existing_nullable=True)
    # ### end Alembic commands ###
