"""add cascade delete to passages file_id

Revision ID: 8939dc3a219e
Revises: 7ed43eddf32e
Create Date: 2024-12-10 07:29:21.241676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8939dc3a219e'
down_revision: Union[str, None] = '7ed43eddf32e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('passages_file_id_fkey', 'passages', type_='foreignkey')
    op.create_foreign_key(None, 'passages', 'files', ['file_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'passages', type_='foreignkey')
    op.create_foreign_key('passages_file_id_fkey', 'passages', 'files', ['file_id'], ['id'])
    # ### end Alembic commands ###
