"""update jobs user cascade delete

Revision ID: efd8c8513fb2
Revises: 8bcc53a82e7c
Create Date: 2024-12-10 06:55:44.201902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efd8c8513fb2'
down_revision: Union[str, None] = '8bcc53a82e7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
