"""Rename block.name to block.template_name

Revision ID: eff245f340f9
Revises: 0c315956709d
Create Date: 2024-10-31 18:09:08.819371

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eff245f340f9"
down_revision: Union[str, None] = "ee50a967e090"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("block", "name", new_column_name="template_name", existing_type=sa.String(), nullable=True)

    # op.add_column('block', sa.Column('template_name', sa.String(), nullable=True))
    # op.drop_column('block', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("block", "template_name", new_column_name="name", existing_type=sa.String(), nullable=True)
    # op.add_column('block', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # op.drop_column('block', 'template_name')
    # ### end Alembic commands ###
