"""Add source table

Revision ID: fcb07dfbc98f
Revises: eff245f340f9
Create Date: 2024-11-04 17:25:39.841950

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from letta.orm.source import EmbeddingConfigColumn

# revision identifiers, used by Alembic.
revision: str = "fcb07dfbc98f"
down_revision: Union[str, None] = "eff245f340f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("embedding_config", EmbeddingConfigColumn(), nullable=False),
        sa.Column("metadata_", sa.JSON(), nullable=True),
        sa.Column("_organization_id", sa.String(), nullable=False),
        sa.Column("_id", sa.String(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False),
        sa.Column("_created_by_id", sa.String(), nullable=True),
        sa.Column("_last_updated_by_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["_organization_id"],
            ["organization._id"],
        ),
        sa.PrimaryKeyConstraint("_id"),
        sa.UniqueConstraint("name", "_organization_id", name="uix_source_name_organization"),
    )
    op.drop_index("sources_idx_user", table_name="sources")
    op.drop_table("sources")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sources",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), autoincrement=False, nullable=True),
        sa.Column("embedding_config", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("metadata_", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="sources_pkey"),
    )
    op.create_index("sources_idx_user", "sources", ["user_id"], unique=False)
    op.drop_table("source")
    # ### end Alembic commands ###
