name: Run All pytest Tests

env:
  MEMGPT_PGURI: ${{ secrets.MEMGPT_PGURI }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v4


    - name: "Setup Python, Poetry and Dependencies"
      uses: packetcoders/action-setup-cache-python-poetry@main
      with:
        python-version: "3.12"
        poetry-version: "1.8.2"
        install-args: "--all-extras"

    - name: Initialize credentials
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        poetry run memgpt quickstart --backend memgpt

    - name: Start Ollama Server
      run: |
        curl -fsSL https://ollama.com/install.sh | sh
        ollama serve &
        ollama pull llama3        

    - name: Test endpoints
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        poetry run pytest -s -vv tests/test_endpoints.py
