name: Test CLI

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-cli:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    services:
      qdrant:
        image: qdrant/qdrant
        ports:
          - 6333:6333
      postgres:
        image: pgvector/pgvector:pg17
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: "Setup Python, Poetry and Dependencies"
      uses: packetcoders/action-setup-cache-python-poetry@main
      with:
        python-version: "3.12"
        poetry-version: "1.8.2"
        install-args: "-E dev -E postgres -E tests"

    - name: Migrate database
      env:
        LETTA_PG_PORT: 5432
        LETTA_PG_USER: postgres
        LETTA_PG_PASSWORD: postgres
        LETTA_PG_DB: postgres
        LETTA_PG_HOST: localhost
      run: |
        psql -h localhost -U postgres -d postgres -c 'CREATE EXTENSION vector'
        poetry run alembic upgrade head

    - name: Test `letta run` up until first message
      env:
        LETTA_PG_PORT: 5432
        LETTA_PG_USER: postgres
        LETTA_PG_PASSWORD: postgres
        LETTA_PG_DB: postgres
        LETTA_PG_HOST: localhost
        LETTA_SERVER_PASS: test_server_token
      run: |
        poetry run pytest -s -vv tests/test_cli.py::test_letta_run_create_new_agent
